### ISSUE TITLE
Make GitHub Pages site

### ISSUE THREAD

**Issue by aknuds1** [aknuds1/chuckjs#2]
Make GitHub Pages site for ChucKJS, with examples prominently displayed so people can easily demo the features.

**Comment by hughrawlinson** [comment]
I'm willing to do this if someone can give me a list of the specific things this site should do.

**Comment by aknuds1** [comment]
Hi @hughrawlinson, thanks for wanting to help out! Work has moved to [my ChucK fork](https://github.com/aknuds1/chuck) though as far as I am concerned, is it OK for you if we move the issue there?

The reason is it should be more fruitful to auto port ChucK via Emscripten rather than manually, I just got stuck due to memory bugs that I couldn't debug due to source mapping issues with Emscripten. Maybe it's got better in the meantime.

**Comment by hughrawlinson** [comment]
Ok, cool, that sounds fun :)
